servers:

  operation-servers:
    own-oam:
      basic:
        - service-name: /v1/register-yourself
          uuid: alt-2-0-0-op-s-bm-000
        - service-name: /v1/embed-yourself
          uuid: alt-2-0-0-op-s-bm-001
        - service-name: /v1/redirect-service-request-information
          uuid: alt-2-0-0-op-s-bm-002
        - service-name: /v1/redirect-oam-request-information
          uuid: alt-2-0-0-op-s-bm-003
        - service-name: /v1/end-subscription
          uuid: alt-2-0-0-op-s-bm-004
        - service-name: /v1/inquire-oam-request-approvals
          uuid: alt-2-0-0-op-s-bm-005
        - service-name: /v1/update-client
          uuid: alt-2-0-0-op-s-bm-007
        - service-name: /v1/list-ltps-and-fcs
          uuid: alt-2-0-0-op-s-bm-008
        - service-name: /v1/redirect-topology-change-information
          uuid: alt-2-0-0-op-s-bm-009
        - service-name: /v1/update-operation-key
          uuid: alt-2-0-0-op-s-bm-010
        - service-name: /v1/update-operation-client
          uuid: alt-2-0-0-op-s-bm-011
      individual:
        - service-name: /v1/bequeath-your-data-and-die
          uuid: alt-2-0-0-op-s-im-000
    service:
      basic:
        - service-name: /v1/start-application-in-generic-representation
          uuid: alt-2-0-0-op-s-bs-000
        - service-name: /v1/inform-about-application
          uuid: alt-2-0-0-op-s-bs-001
        - service-name: /v1/inform-about-application-in-generic-representation
          uuid: alt-2-0-0-op-s-bs-002
        - service-name: /v1/inform-about-release-history
          uuid: alt-2-0-0-op-s-bs-003
        - service-name: /v1/inform-about-release-history-in-generic-representation
          uuid: alt-2-0-0-op-s-bs-004
        - service-name: /docs
          uuid: alt-2-0-0-op-s-bs-005
      individual:
        - service-name: /v1/regard-application
          uuid: alt-2-0-0-op-s-is-001
        - service-name: /v1/disregard-application
          uuid: alt-2-0-0-op-s-is-002
        - service-name: /v1/list-applications
          uuid: alt-2-0-0-op-s-is-003
        - service-name: /v1/update-all-ltps-and-fcs
          uuid: alt-2-0-0-op-s-is-004
        - service-name: /v1/update-ltp
          uuid: alt-2-0-0-op-s-is-005
        - service-name: /v1/delete-ltp-and-dependents
          uuid: alt-2-0-0-op-s-is-006
        - service-name: /v1/list-operation-servers-at-application
          uuid: alt-2-0-0-op-s-is-009
        - service-name: /v1/list-operation-clients-at-application
          uuid: alt-2-0-0-op-s-is-010
        - service-name: /v1/update-fc
          uuid: alt-2-0-0-op-s-is-013
        - service-name: /v1/update-fc-port
          uuid: alt-2-0-0-op-s-is-014
        - service-name: /v1/delete-fc-port
          uuid: alt-2-0-0-op-s-is-015
        - service-name: /v1/list-operation-clients-reacting-on-operation-server
          uuid: alt-2-0-0-op-s-is-016
        - service-name: /v1/list-link-uuids
          uuid: alt-2-0-0-op-s-is-017
        - service-name: /v1/add-operation-client-to-link
          uuid: alt-2-0-0-op-s-is-018
        - service-name: /v1/remove-operation-client-from-link
          uuid: alt-2-0-0-op-s-is-019
        - service-name: /v1/list-end-points-of-link
          uuid: alt-2-0-0-op-s-is-020
        - service-name: /v1/list-links-to-operation-clients-of-application
          uuid: alt-2-0-0-op-s-is-021
        - service-name: /v1/notify-link-updates
          uuid: alt-2-0-0-op-s-is-022
  http-server:
    own-application-name: ApplicationLayerTopology
    own-release-number: 2.0.0
    uuid: alt-2-0-0-http-s-is-000
  tpc-server:
    - description: Without TLS layer
      local-protocol: http
      own-ip-address: 1.1.3.13
      own-tcp-port: 3013
      uuid: alt-2-0-0-tcp-s-is-000
    - description: With TLS layer
      local-protocol: https
      own-ip-address: 1.2.3.13
      own-tcp-port: 3213
      uuid: alt-2-0-0-tcp-s-is-001


clients:

  - http-client:
      application-name: OldRelease
      release-number: 1.0.0
      uuid: alt-2-0-0-http-c-bm-or-1-0-0-000
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1005
      uuid: alt-2-0-0-tcp-c-bm-or-1-0-0-000
    operation-clients:
      own-oam:
        basic:
          - service-name: /v1/bequeath-your-data-and-die
            uuid: alt-2-0-0-op-c-bm-or-1-0-0-000
        individual:
      service:
        basic:
        individual:

  - http-client:
      application-name: NewRelease
      release-number: 2.0.0
      uuid: alt-2-0-0-http-c-im-nr-2-0-0-000
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1005
      uuid: alt-2-0-0-tcp-c-im-nr-2-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
          - service-name: /v1/regard-application
            uuid: alt-2-0-0-op-c-im-nr-2-0-0-000
          - service-name: /v1/update-all-ltps-and-fcs
            uuid: alt-2-0-0-op-c-im-nr-2-0-0-001
          - service-name: /v1/add-operation-client-to-link
            uuid: alt-2-0-0-op-c-im-nr-2-0-0-002
      service:
        basic:
        individual:

  - http-client:
      application-name: RegistryOffice
      release-number: 2.0.0
      uuid: alt-2-0-0-http-c-bm-ro-2-0-0-000
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1000
      uuid: alt-2-0-0-tcp-c-bm-ro-2-0-0-000
    operation-clients:
      own-oam:
        basic:
          - service-name: /v1/register-application
            uuid: alt-2-0-0-op-c-bm-ro-2-0-0-000
          - service-name: /v1/relay-server-replacement
            uuid: alt-2-0-0-op-c-bm-ro-2-0-0-001
          - service-name: /v1/deregister-application
            uuid: alt-2-0-0-op-c-bm-ro-2-0-0-002
          - service-name: /v1/relay-operation-update
            uuid: alt-2-0-0-op-c-bm-ro-2-0-0-003
        individual:
          - service-name: /v1/notify-approvals
            uuid: alt-2-0-0-op-c-im-ro-2-0-0-000
          - service-name: /v1/notify-withdrawn-approvals
            uuid: alt-2-0-0-op-c-im-ro-2-0-0-001
          - service-name: /v1/end-subscription
            uuid: alt-2-0-0-op-c-im-ro-2-0-0-002
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-2-0-0-op-c-im-ro-2-0-0-004
      service:
        basic:
        individual:
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-2-0-0-op-c-is-ro-2-0-0-001

  - http-client:
      application-name: TypeApprovalRegister
      release-number: 1.0.0
      uuid: alt-2-0-0-http-c-im-tar-1-0-0-000
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1001
      uuid: alt-2-0-0-tcp-c-im-tar-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-2-0-0-op-c-im-tar-1-0-0-000
      service:
        basic:
        individual:
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-2-0-0-op-c-is-tar-1-0-0-001

  - http-client:
      application-name: ExecutionAndTraceLog
      release-number: 1.0.0
      uuid: alt-2-0-0-http-c-im-eatl-1-0-0-000
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1002
      uuid: alt-2-0-0-tcp-c-im-eatl-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-2-0-0-op-c-im-eatl-1-0-0-000
      service:
        basic:
          - service-name: /v1/record-service-request
            uuid: alt-2-0-0-op-c-bs-eatl-1-0-0-000
        individual:
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-2-0-0-op-c-is-eatl-1-0-0-001

  - http-client:
      application-name: OamLog
      release-number: 1.0.0
      uuid: alt-2-0-0-http-c-im-ol-1-0-0-000
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1003
      uuid: alt-2-0-0-tcp-c-im-ol-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-2-0-0-op-c-im-ol-1-0-0-000
      service:
        basic:
          - service-name: /v1/record-oam-request
            uuid: alt-2-0-0-op-c-bs-ol-1-0-0-000
        individual:
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-2-0-0-op-c-is-ol-1-0-0-001

  - http-client:
      application-name: AdministratorAdministration
      release-number: 1.0.0
      uuid: alt-2-0-0-http-c-im-aa-1-0-0-000
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1004
      uuid: alt-2-0-0-tcp-c-im-aa-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-2-0-0-op-c-im-aa-1-0-0-000
      service:
        basic:
          - service-name: /v1/approve-oam-request
            uuid: alt-2-0-0-op-c-bs-aa-1-0-0-000
        individual:
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-2-0-0-op-c-is-aa-1-0-0-001

  - http-client:
      application-name: ApplicationLayerTopology
      release-number: 2.0.0
      uuid: alt-2-0-0-http-c-bm-alt-2-0-0-000
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1005
      uuid: alt-2-0-0-tcp-c-bm-alt-2-0-0-000
    operation-clients:
      own-oam:
        basic:
          - service-name: /v1/update-all-ltps-and-fcs
            uuid: alt-2-0-0-op-c-bm-alt-2-0-0-000
          - service-name: /v1/update-ltp
            uuid: alt-2-0-0-op-c-bm-alt-2-0-0-001
          - service-name: /v1/delete-ltp-and-dependents
            uuid: alt-2-0-0-op-c-bm-alt-2-0-0-002
          - service-name: /v1/update-fc
            uuid: alt-2-0-0-op-c-bm-alt-2-0-0-003
          - service-name: /v1/update-fc-port
            uuid: alt-2-0-0-op-c-bm-alt-2-0-0-004
          - service-name: /v1/delete-fc-port
            uuid: alt-2-0-0-op-c-bm-alt-2-0-0-005
        individual:
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-2-0-0-op-c-im-alt-2-0-0-000
      service:
        basic:
        individual:
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-2-0-0-op-c-is-alt-2-0-0-001

  - http-client:
      application-name: OperationKeyManagement
      release-number: 1.0.0
      uuid: alt-2-0-0-http-c-is-okm-1-0-0-000
    tcp-client:
      ip-address: 10.118.125.157
      tcp-port: 1006
      uuid: alt-2-0-0-tcp-c-is-okm-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-2-0-0-op-c-im-okm-1-0-0-000
      service:
        basic:
        individual:
          - service-name: /v1/regard-updated-link
            uuid: alt-2-0-0-op-c-is-okm-1-0-0-000
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-2-0-0-op-c-is-okm-1-0-0-001

  - http-client:
      application-name: CurrentController
      release-number: 1.0.0
      uuid: alt-2-0-0-http-c-im-cc-1-0-0-000
    tcp-client:
      ip-address: 10.118.125.186
      tcp-port: 2000
      uuid: alt-2-0-0-tcp-c-im-cc-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
          - service-name: /v1/redirect-topology-change-information
            uuid: alt-2-0-0-op-c-im-cc-1-0-0-000
      service:
        basic:
        individual:
          - service-name: /v1/list-ltps-and-fcs
            uuid: alt-2-0-0-op-c-is-cc-1-0-0-001