servers:

  operation-servers:
    own-oam:
      basic:
        - operation-name: /v1/register-yourself
          uuid: alt-2-0-1-op-s-bm-000
        - operation-name: /v1/embed-yourself
          uuid: alt-2-0-1-op-s-bm-001
        - operation-name: /v1/redirect-service-request-information
          uuid: alt-2-0-1-op-s-bm-002
        - operation-name: /v1/redirect-oam-request-information
          uuid: alt-2-0-1-op-s-bm-003
        - operation-name: /v1/end-subscription
          uuid: alt-2-0-1-op-s-bm-004
        - operation-name: /v1/inquire-oam-request-approvals
          uuid: alt-2-0-1-op-s-bm-005
        - operation-name: /v1/update-client
          uuid: alt-2-0-1-op-s-bm-007
        - operation-name: /v1/list-ltps-and-fcs
          uuid: alt-2-0-1-op-s-bm-008
        - operation-name: /v1/redirect-topology-change-information
          uuid: alt-2-0-1-op-s-bm-009
        - operation-name: /v1/update-operation-key
          uuid: alt-2-0-1-op-s-bm-010
        - operation-name: /v1/update-operation-client
          uuid: alt-2-0-1-op-s-bm-011
      individual:
        - operation-name: /v1/bequeath-your-data-and-die
          uuid: alt-2-0-1-op-s-im-000
    service:
      basic:
        - operation-name: /v1/start-application-in-generic-representation
          uuid: alt-2-0-1-op-s-bs-000
        - operation-name: /v1/inform-about-application
          uuid: alt-2-0-1-op-s-bs-001
        - operation-name: /v1/inform-about-application-in-generic-representation
          uuid: alt-2-0-1-op-s-bs-002
        - operation-name: /v1/inform-about-release-history
          uuid: alt-2-0-1-op-s-bs-003
        - operation-name: /v1/inform-about-release-history-in-generic-representation
          uuid: alt-2-0-1-op-s-bs-004
        - operation-name: /docs
          uuid: alt-2-0-1-op-s-bs-005
      individual:
        - operation-name: /v1/regard-application
          uuid: alt-2-0-1-op-s-is-001
        - operation-name: /v1/disregard-application
          uuid: alt-2-0-1-op-s-is-002
        - operation-name: /v1/list-applications
          uuid: alt-2-0-1-op-s-is-003
        - operation-name: /v1/update-all-ltps-and-fcs
          uuid: alt-2-0-1-op-s-is-004
        - operation-name: /v1/update-ltp
          uuid: alt-2-0-1-op-s-is-005
        - operation-name: /v1/delete-ltp-and-dependents
          uuid: alt-2-0-1-op-s-is-006
        - operation-name: /v1/list-operation-servers-at-application
          uuid: alt-2-0-1-op-s-is-009
        - operation-name: /v1/list-operation-clients-at-application
          uuid: alt-2-0-1-op-s-is-010
        - operation-name: /v1/update-fc
          uuid: alt-2-0-1-op-s-is-013
        - operation-name: /v1/update-fc-port
          uuid: alt-2-0-1-op-s-is-014
        - operation-name: /v1/delete-fc-port
          uuid: alt-2-0-1-op-s-is-015
        - operation-name: /v1/list-operation-clients-reacting-on-operation-server
          uuid: alt-2-0-1-op-s-is-016
        - operation-name: /v1/list-link-uuids
          uuid: alt-2-0-1-op-s-is-017
        - operation-name: /v1/add-operation-client-to-link
          uuid: alt-2-0-1-op-s-is-018
        - operation-name: /v1/remove-operation-client-from-link
          uuid: alt-2-0-1-op-s-is-019
        - operation-name: /v1/list-end-points-of-link
          uuid: alt-2-0-1-op-s-is-020
        - operation-name: /v1/list-links-to-operation-clients-of-application
          uuid: alt-2-0-1-op-s-is-021
        - operation-name: /v1/notify-link-updates
          uuid: alt-2-0-1-op-s-is-022
  http-server:
    own-application-name: ApplicationLayerTopology
    own-release-number: 2.0.1
    uuid: alt-2-0-1-http-s-000
  tpc-server:
    - description: Without TLS layer
      local-protocol: http
      own-ip-address: 1.1.3.13
      own-tcp-port: 3013
      uuid: alt-2-0-1-tcp-s-000


clients:

  - http-client:
      application-name: ElasticSearch
      release-number: 1.0.0
      uuid: alt-2-0-1-http-c-es-1-0-0-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.3.15
      tcp-port: 3015
      uuid: alt-2-0-1-tcp-c-es-1-0-0-000
    elasticsearch-client:
      uuid: alt-2-0-1-es-c-es-1-0-0-000
      index-alias: alt-2-0-1

  - http-client:
      application-name: OldRelease
      release-number: 1.0.0
      uuid: alt-2-0-1-http-c-or-1-0-0-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.3.6
      tcp-port: 3006
      uuid: alt-2-0-1-tcp-c-or-1-0-0-000
    operation-clients:
      own-oam:
        basic:
          - operation-name: /v1/bequeath-your-data-and-die
            uuid: alt-2-0-1-op-c-bm-or-1-0-0-000
        individual:
      service:
        basic:
        individual:

  - http-client:
      application-name: NewRelease
      release-number: 2.0.1
      uuid: alt-2-0-1-http-c-nr-2-0-1-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.3.13
      tcp-port: 3013
      uuid: alt-2-0-1-tcp-c-nr-2-0-1-000
    operation-clients:
      own-oam:
        basic:
        individual:
          - operation-name: /v1/regard-application
            uuid: alt-2-0-1-op-c-im-nr-2-0-1-000
          - operation-name: /v1/update-all-ltps-and-fcs
            uuid: alt-2-0-1-op-c-im-nr-2-0-1-001
          - operation-name: /v1/add-operation-client-to-link
            uuid: alt-2-0-1-op-c-im-nr-2-0-1-002
      service:
        basic:
        individual:

  - http-client:
      application-name: RegistryOffice
      release-number: 2.0.1
      uuid: alt-2-0-1-http-c-ro-2-0-1-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.3.8
      tcp-port: 3008
      uuid: alt-2-0-1-tcp-c-ro-2-0-1-000
    operation-clients:
      own-oam:
        basic:
          - operation-name: /v1/register-application
            uuid: alt-2-0-1-op-c-bm-ro-2-0-1-000
          - operation-name: /v1/relay-server-replacement
            uuid: alt-2-0-1-op-c-bm-ro-2-0-1-001
          - operation-name: /v1/deregister-application
            uuid: alt-2-0-1-op-c-bm-ro-2-0-1-002
          - operation-name: /v1/relay-operation-update
            uuid: alt-2-0-1-op-c-bm-ro-2-0-1-003
        individual:
          - operation-name: /v1/notify-approvals
            uuid: alt-2-0-1-op-c-im-ro-2-0-1-000
          - operation-name: /v1/notify-withdrawn-approvals
            uuid: alt-2-0-1-op-c-im-ro-2-0-1-001
          - operation-name: /v1/end-subscription
            uuid: alt-2-0-1-op-c-im-ro-2-0-1-002
          - operation-name: /v1/redirect-topology-change-information
            uuid: alt-2-0-1-op-c-im-ro-2-0-1-004
      service:
        basic:
        individual:

  - http-client:
      application-name: TypeApprovalRegister
      release-number: 1.0.0
      uuid: alt-2-0-1-http-c-tar-1-0-0-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.3.2
      tcp-port: 3002
      uuid: alt-2-0-1-tcp-c-tar-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
          - operation-name: /v1/redirect-topology-change-information
            uuid: alt-2-0-1-op-c-im-tar-1-0-0-004
      service:
        basic:
        individual:

  - http-client:
      application-name: ExecutionAndTraceLog
      release-number: 1.0.0
      uuid: alt-2-0-1-http-c-eatl-1-0-0-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.3.3
      tcp-port: 3003
      uuid: alt-2-0-1-tcp-c-eatl-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
          - operation-name: /v1/redirect-topology-change-information
            uuid: alt-2-0-1-op-c-im-eatl-1-0-0-004
      service:
        basic:
          - operation-name: /v1/record-service-request
            uuid: alt-2-0-1-op-c-bs-eatl-1-0-0-000
        individual:

  - http-client:
      application-name: OamLog
      release-number: 1.0.0
      uuid: alt-2-0-1-http-c-ol-1-0-0-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.3.4
      tcp-port: 3004
      uuid: alt-2-0-1-tcp-c-ol-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
          - operation-name: /v1/redirect-topology-change-information
            uuid: alt-2-0-1-op-c-im-ol-1-0-0-004
      service:
        basic:
          - operation-name: /v1/record-oam-request
            uuid: alt-2-0-1-op-c-bs-ol-1-0-0-000
        individual:

  - http-client:
      application-name: AdministratorAdministration
      release-number: 1.0.0
      uuid: alt-2-0-1-http-c-aa-1-0-0-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.3.5
      tcp-port: 3005
      uuid: alt-2-0-1-tcp-c-aa-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
          - operation-name: /v1/redirect-topology-change-information
            uuid: alt-2-0-1-op-c-im-aa-1-0-0-004
      service:
        basic:
          - operation-name: /v1/approve-oam-request
            uuid: alt-2-0-1-op-c-bs-aa-1-0-0-000
        individual:

  - http-client:
      application-name: ApplicationLayerTopology
      release-number: 2.0.2
      uuid: alt-2-0-1-http-c-alt-2-0-1-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.3.22
      tcp-port: 3022
      uuid: alt-2-0-1-tcp-c-alt-2-0-1-000
    operation-clients:
      own-oam:
        basic:
          - operation-name: /v1/update-all-ltps-and-fcs
            uuid: alt-2-0-1-op-c-bm-alt-2-0-1-000
          - operation-name: /v1/update-ltp
            uuid: alt-2-0-1-op-c-bm-alt-2-0-1-001
          - operation-name: /v1/delete-ltp-and-dependents
            uuid: alt-2-0-1-op-c-bm-alt-2-0-1-002
          - operation-name: /v1/update-fc
            uuid: alt-2-0-1-op-c-bm-alt-2-0-1-003
          - operation-name: /v1/update-fc-port
            uuid: alt-2-0-1-op-c-bm-alt-2-0-1-004
          - operation-name: /v1/delete-fc-port
            uuid: alt-2-0-1-op-c-bm-alt-2-0-1-005
        individual:
          - operation-name: /v1/redirect-topology-change-information
            uuid: alt-2-0-1-op-c-im-alt-2-0-1-004
      service:
        basic:
        individual:
          - operation-name: /v1/add-operation-client-to-link
            uuid: alt-2-0-1-op-c-is-alt-2-0-1-000
          - operation-name: /v1/remove-operation-client-from-link
            uuid: alt-2-0-1-op-c-is-alt-2-0-1-001

  - http-client:
      application-name: OperationKeyManagement
      release-number: 1.0.0
      uuid: alt-2-0-1-http-c-okm-1-0-0-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.3.7
      tcp-port: 3007
      uuid: alt-2-0-1-tcp-c-okm-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
          - operation-name: /v1/redirect-topology-change-information
            uuid: alt-2-0-1-op-c-im-okm-1-0-0-004
      service:
        basic:
        individual:
          - operation-name: /v1/regard-updated-link
            uuid: alt-2-0-1-op-c-is-okm-1-0-0-002
